<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/goods.proto

namespace GPBMetadata\Pb;

class Goods
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ï
pb/goods.protogoods"
GoodsRequest

id ("/
GoodsResponse
list (2.goods.GoodsInfo"3
	GoodsInfo

id (
name (	
tags (	2A
GoodsService1
Find.goods.GoodsRequest.goods.GoodsResponseB	Z./goodsbproto3'
        , true);

        static::$is_initialized = true;
    }
}

